version: '3'

services:
  cmdb-js-server:
    build: ./server
    ports:
      - "8082:8080"

  cmdb-js-client:
    depends_on:
      - cmdb-js-server
    build: ./client
    ports:
      - "8081:8080"
